name = "cyrius-doom"
version = "0.26.1"
license = "GPL-3.0-only"
entry = "src/main.cyr"
output = "doom"
description = "DOOM in Cyrius — 129KB, direct framebuffer, no libc, just syscalls."
repository = "https://github.com/MacCracken/cyrius-doom"

[deps]
stdlib = ["string", "alloc", "fmt", "vec", "str", "io", "fs", "args", "syscalls", "hashmap", "tagged", "fnptr", "freelist", "process", "patra", "sakshi"]

[deps.bsp]
git = "https://github.com/MacCracken/bsp"
tag = "1.1.2"
modules = ["dist/bsp.cyr"]

[deps.vani]
git = "https://github.com/MacCracken/vani"
tag = "0.9.0"
modules = ["dist/vani.cyr"]
